### ISSUE TITLE
docs: markdown issue in code snippets (due to indentation)

### ISSUE THREAD

**Issue by orozcoadrian** [awslabs/serverless-rules#59] opened 2021-06-12 00:30 UTC
Please see my comment here: https://github.com/awslabs/serverless-rules/pull/58#issuecomment-858972377

I have verified that the issue is fixed by removing the indentation (using the vscode preview pane). It looks like there's about 125 cases of indented code snippets in the repo. If this fix is desired (and the proposed implementation acceptable) then I can open a PR. Let me know.

**Comment by nmoutschen** [comment] 2021-06-12 10:32
Hey @orozcoadrian !

Thanks for opening this issue! I know it looks like a bug in GitHub, but it's actually by design. 😄 The `docs/` folder is used to generate the [documentation website](https://awslabs.github.io/serverless-rules/) with mkdocs. During the generation process, it uses [Admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) and [SuperFences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/), which allow nesting code blocks, but GitHub markdown doesn't support it.

The documentation you linked in #58 correspond to [this page](https://awslabs.github.io/serverless-rules/cfn-lint/#sample-outputs) in the documentation, where it works properly.

**Comment by nmoutschen** [comment] 2021-06-14 16:34
Hey @orozcoadrian ! I'm closing this issue now since there are no more actions here, but thanks again for opening it and proposing your help.

**Closed by nmoutschen** 2021-06-14 16:34 UTC
